function createStaffRows(numRows) {
  let htmlStr = "";
  for (let i = 0; i < numRows; i++) {
    htmlStr += '<div class="staff-row">';
    htmlStr += '<div class="staff treble-clef">';
    htmlStr += '<div class="clef"></div>';
    htmlStr += '<div class="staff-lines">';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += "</div>";
    htmlStr += '<div class="hitareas">';

    for (let j = 0; j < 4; j++) {
      htmlStr += createBar(i, "t", j);
    }

    htmlStr += "</div>";
    htmlStr += "</div>";
    htmlStr += '<div class="staff bass-clef">';
    htmlStr += '<div class="clef"></div>';
    htmlStr += '<div class="staff-lines">';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += '<div class="space"></div>';
    htmlStr += '<div class="line"></div>';
    htmlStr += "</div>";
    htmlStr += '<div class="hitareas">';

    for (let j = 0; j < 4; j++) {
      htmlStr += createBassBar(i, "b", j);
    }

    htmlStr += "</div>";
    htmlStr += "</div>";
    htmlStr += "</div>";
    htmlStr += "</div>";
  }
  return htmlStr;
}

function createBar(staffId, clef, barId) {
  let htmlStr = "";
  htmlStr += "";
  htmlStr += `<div class="bar" id="bar-${staffId}-${clef}${barId}">`;
  htmlStr += `<div class="notes" id="notes-${staffId}-${clef}${barId}"></div>`;
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="f5"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="e5"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="d5"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="c5"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="b4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="a4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="g4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="f4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="e4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="d4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="c4"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "</div>";
  return htmlStr;
}
function createBassBar(staffId, clef, barId) {
  let htmlStr = "";
  htmlStr += "";
  htmlStr += `<div class="bar" id="bar-${staffId}-${clef}${barId}">`;
  htmlStr += `<div class="notes" id="notes-${staffId}-${clef}${barId}"></div>`;
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="a3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="g3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="f3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="e3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="d3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="c3"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="b2"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="a2"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="g2"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea space"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="f2"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "<div ";
  htmlStr += 'class="hitarea line"';
  htmlStr += `data-staff-id="${staffId}"`;
  htmlStr += `data-bar-id="${barId}"`;
  htmlStr += 'data-key="e2"';
  htmlStr += `data-clef="${clef}"`;
  htmlStr += "></div>";
  htmlStr += "</div>";
  return htmlStr;
}
